#!/bin/bash

set -x
set -e

# Usage
#  -d = show diff
#  -u = update config in git repo



GetoptsVariables() {
    while getopts ":d:u:" opt; do
        case ${opt} in
            d)
                SIMPLE_FILE_NAME="${OPTARG}"
                case "${SIMPLE_FILE_NAME}" in
                    bashrc|bash)
                        diff -u $(pwd)/.bashrc ~/.bashrc
                        ;;
                    tmux|tm)
                        diff -u $(pwd)/.tmux.conf ~/.tmux.conf
                        ;;
                    terminator|term)
                        diff -u $(pwd)/.config/terminator/config ~/.config/terminator/config
                esac
                ;;
            u)
                SIMPLE_FILE_NAME="${OPTARG}"
                if [ -z "${SIMPLE_FILE_NAME}" ];then 
                    cp ~/.bashrc $(pwd)/.bashrc
                    cp ~/.tmux.conf $(pwd)/.tmux
                    cp ~/.config/terminator/config $(pwd)/.config/terminator/config
                fi
                case "${SIMPLE_FILE_NAME}" in
                    bashrc|bash)
                        cp ~/.bashrc $(pwd)/.bashrc
                        ;;
                    tmux|tm)
                        cp ~/.tmux.conf $(pwd)/.tmux.conf
                        ;;
                    terminator|term)
                        cp ~/.config/terminator/config $(pwd)/.config/terminator/config
                esac
                ;;
            *)
                echo "Wrong option"
                exit 1
        esac
    done
}





GetoptsVariables ${@}

